services:
  redis:
    image: redis:7
    container_name: redis-test
    ports:
      - "6379:6379"
    restart: unless-stopped

  gps-service-mock:
    build: ./gps-service-sim
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  lag-service-mock:
    build: ./lag-service-sim
    container_name: lag-service-mock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  wind-service-mock:
    build: ./wind-service-sim
    container_name: wind-service-mock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  depth-service-mock:
    build: ./depth-service-sim
    container_name: depth-service-mock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend-test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: sailing-postgres
    restart: always

    environment:
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: sailpass
      POSTGRES_DB: sailing

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sail -d sailing" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  pgdata:

